/*
 * Copyright (c) 2026, WSO2 LLC. (https://www.wso2.com).
 *
 * WSO2 LLC. licenses this file to you under the Apache License,
 * Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License.
 * You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing,
 * software distributed under the License is distributed on an
 * "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY
 * KIND, either express or implied.  See the License for the
 * specific language governing permissions and limitations
 * under the License.
 */

// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package scim

import (
	"context"

	mock "github.com/stretchr/testify/mock"
)

// NewSCIMServiceInterfaceMock creates a new instance of SCIMServiceInterfaceMock.
// It also registers a testing interface on the mock and a cleanup function to assert
// the mock's expectations.
// The first argument is typically a *testing.T value.
func NewSCIMServiceInterfaceMock(t interface {
	mock.TestingT
	Cleanup(func())
}) *SCIMServiceInterfaceMock {
	m := &SCIMServiceInterfaceMock{}
	m.Mock.Test(t)
	t.Cleanup(func() { m.AssertExpectations(t) })
	return m
}

// SCIMServiceInterfaceMock is an autogenerated mock type for the SCIMServiceInterface type.
type SCIMServiceInterfaceMock struct {
	mock.Mock
}

// SCIMServiceInterfaceMock_Expecter provides type-safe On() chaining.
type SCIMServiceInterfaceMock_Expecter struct {
	mock *mock.Mock
}

// EXPECT returns the expecter for fluent mock setup.
func (_m *SCIMServiceInterfaceMock) EXPECT() *SCIMServiceInterfaceMock_Expecter {
	return &SCIMServiceInterfaceMock_Expecter{mock: &_m.Mock}
}

// GetServiceProviderConfig provides a mock function for the type SCIMServiceInterfaceMock.
func (_mock *SCIMServiceInterfaceMock) GetServiceProviderConfig(
	ctx context.Context,
	baseURL string,
) SCIMServiceProviderConfig {
	ret := _mock.Called(ctx, baseURL)

	if len(ret) == 0 {
		panic("no return value specified for GetServiceProviderConfig")
	}

	var r0 SCIMServiceProviderConfig
	if returnFunc, ok := ret.Get(0).(func(context.Context, string) SCIMServiceProviderConfig); ok {
		r0 = returnFunc(ctx, baseURL)
	} else {
		r0 = ret.Get(0).(SCIMServiceProviderConfig)
	}
	return r0
}

// GetServiceProviderConfig is a helper method to define mock.On call.
func (_e *SCIMServiceInterfaceMock_Expecter) GetServiceProviderConfig(
	ctx interface{},
	baseURL interface{},
) *mock.Call {
	return _e.mock.On("GetServiceProviderConfig", ctx, baseURL)
}
